### ISSUE TITLE
Support for satellite data

### ISSUE THREAD

**Issue by Geethen** [bnsreenu/digitalsreeni-image-annotator#3] opened 2024-09-28 19:01 UTC
The pre-existing [IRIS tool](https://github.com/ESA-PhiLab/iris) has some useful features like the paint brush that can change size and annotations that can then be erased and edited in a human-in-the-loop manner. Support for multiple linked views- especially useful when dealing with multispectral satellite data. The hotkeys are also very intuitive. 

[More about IRIS](https://www.youtube.com/watch?v=ERJA2-fTW6k&ab_channel=RobinCole)

Adding these features into the image annotator would be beneficial for annotation in general.

**Comment by bnsreenu** [comment] 2024-11-15 22:11
Closing the issue as the application is not designed to handle multispectral satellite images. So not a bug of the application but rather a new feature request.

**Closed** 2024-11-15 22:10 UTC
