### ISSUE TITLE
Unable to load SAM module

### ISSUE THREAD

**Issue by mohdsinad** [bnsreenu/digitalsreeni-image-annotator#2] opened 2024-09-19 17:01 UTC
![error](https://github.com/user-attachments/assets/4af19357-baae-42f9-b035-5c3c459f2275)

I get the above error when I try to load in the SAM2 .yaml config and .pt checkpoint files.

P.S. I follow your videos online. Really informative! and Thank you for creating this annotation tool.

**Comment by bnsreenu** [comment] 2024-09-19 18:23
Thanks for watching my YouTube tutorials :)
Regarding your issue, did you try sam2_hiera_s.yaml or sam2_hiera_t.yaml? If so, did they work? I did not test the base plus model. I wonder if the issue is with the + sign in the yaml file name. Can you change it to sam2_hiera_b_plus.yaml and see if it works?

**Comment by bnsreenu** [comment] 2024-09-19 18:30
I just tested with sam2_hiera_b+.yaml and accompanying sam2_hiera_base_plus.pt, it worked perfectly fine. Did you download the model and place it locally? Can you tell more about the system you are using, is it a mac, Windows or Linux?

![image](https://github.com/user-attachments/assets/86149a85-f50c-4415-84b9-50993ce408e5)

**Comment by mohdsinad** [comment] 2024-09-20 00:27
Hi,

Thank you for the quick reply. I use an Ubuntu 22.04 based linux distro. 

I have got the config and weight files in my local system (both of them reside in a folder in Downloads). The SAM2 as well as the digitalsreeni-image-annotator (editable version) installation are in a conda environment where pytorch is also installed. 

initially, I thought it was a path issue (load_sam2_model function; before the try block) and checked it out; no issues there. Narrowed it down to the build_sam2 function call. I think the code breaks there and returns the error message.

**Comment by bnsreenu** [comment] 2024-09-20 02:42
I just managed to recreate the issue, on mac and Linux. It works fine on Windows. Must be the way the path is assigned. I will have a look at it this weekend. Thanks for letting me know.

**Comment by bnsreenu** [comment] 2024-09-24 16:53
Can you please check if the latest version fixed the issue. I completely reworked the SAM tool as mac and Ubuntu seem to have issues with my original approach. Now, I am using Ultralytics library so no more manual loading of models and config files.

**Comment by mohdsinad** [comment] 2024-09-25 05:01
I tried out the latest version as you suggested. 

Yes, the Ultralytics approach seems cleaner too. However, I face a new error as shown below.

![image](https://github.com/user-attachments/assets/dc6d07d9-0747-4132-aa79-61d5cee86eaf)

**Comment by bnsreenu** [comment] 2024-09-25 16:01
Since this is a new issue, I will close the current issue to keep these topics separate. Based on the error, it seems to be a system-specific issue to your system and possibly to Ubuntu showing "xcb" plugin for X11-based systems. In summary, it could be how Qt is interacting with the X11 windowing system on your particular setup making it a bit challenging to troubleshoot. I hope someone can test it on other Linux installations and report the issue, if reproducible or better yet help fix it :)

**Comment by bnsreenu** [comment] 2024-09-25 16:02
Closing the current issue of SAM on non-Windows systems.

**Closed by bnsreenu** 2024-09-25 16:01 UTC
